version: "3.7"

services:

  nginx:
    image: nginx:1.19.5
    ports:
      - 80:80
    networks:
      - gis_proj1_network
    volumes:
      - /home/sola0419/nginx.conf:/etc/nginx/nginx.conf
      - gis_prac_static:/data/static/
      - gis_prac_media:/data/media/

  django:
    image: django_solproject:5
    networks:
      - gis_proj1_network
    volumes:
      - gis_prac_static:/home/Django_Practice/staticfiles/
      - gis_prac_media:/home/Django_Practice/media/
    secrets:
      - DJANGO_SECRET_KEY
      - MARIADB_USER
      - MARIADB_PASSWORD

  mariadb:
    image: mariadb:10.5
    networks:
      - gis_proj1_network
    volumes:
      - gis_prac_mariadb:/var/lib/mysql
    secrets:
      - MARIADB_USER
      - MARIADB_PASSWORD
      - MARIADB_ROOT_PASSWORD
    environment:
      MARIADB_DATABASE: django
      MARIADB_USER_FILE: /run/secrets/MARIADB_USER
      MARIADB_PASSWORD_FILE: /run/secrets/MARIADB_PASSWORD
      MARIADB_ROOT_PASSWORD_FILE: /run/secrets/MARIADB_ROOT_PASSWORD

networks:
  gis_proj1_network:

volumes:
  gis_prac_static:
  gis_prac_media:
  gis_prac_mariadb:

secrets:
  DJANGO_SECRET_KEY:
    external: true
  MARIADB_ROOT_PASSWORD:
    external: true
  MARIADB_USER:
    external: true
  MARIADB_PASSWORD:
    external: true